sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t neweco/frontend ./frontend
  - docker build -t neweco/backend ./backend
  - docker build -t neweco/nginx ./nginx

script:
  # login to docker hub
  - echo "$AZURE_REGISTRY_PW" | docker login -u "$AZURE_REGISTRY_ID" --password-stdin "$AZURE_REGISTRY_NAME"

  # push to docker hub
  - docker push neweco/frontend
  - docker push neweco/backend
  - docker push neweco/nginx
  # on:
  #   branch: develop

  #
