version: "3.4"

services:

  nginx:
    restart: always
    image: newecopeoplev1/nginx_dev
    ports:
      - "80:80"

  frontend:
    image: newecopeoplev1/frontend_dev

  backend:
    image: newecopeoplev1/backend