version: "3.4"

services:

  nginx:
    restart: always
    image: newecopeoplev1/nginx_dev
    ports:
      - "80:80"

  frontend:
    image: newecopeoplev1/frontend_dev

  backend:
    image: newecopeoplev1/backend_dev
    environment:
      - DefaultConnection=Filename=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
      - SENDGRID_API=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
      - HOSTNAME=http://localhost