version: "3.4"

services:

  # mssql_image:
  #   image: mcr.microsoft.com/mssql/server
  #   environment:
  #       SA_PASSWORD: "noPassword@247"
  #       ACCEPT_EULA: "Y"

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DefaultConnection=Data Source=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "5000:5000"