version: "3.4"

services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.staging
    environment:
      - DefaultConnection=Filename=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
      - SENDGRID_API=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
      - HOSTNAME=http://localhost
    ports:
      - "5000:5000"